# Simple, clean starship config with icons
format = """$directory$git_branch$git_status$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[](bold yellow)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"
home_symbol = "󰋜"
read_only = " 󰌾"

[git_branch]
symbol = "󰊢 "
format = "[$symbol$branch]($style) "
style = "bold purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold yellow"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "[?${count}](bright-blue)"     	# blue for new files
modified = "[Δ${count}](yellow)"           	# yellow for changes
staged = "[+${count}](green)"              	# green for staged (ready to commit)
deleted = "[✘${count}](red)"              	 # red only for deletions

# Programming languages (only show when relevant)
[nodejs]
symbol = "󰎙 "
format = "[$symbol$version ]($style)"

[python]
symbol = "󰌠 "
format = "[$symbol$version ]($style)"

[rust]
symbol = "󱘗 "
format = "[$symbol$version ]($style)"

[docker_context]
symbol = "󰡨 "
format = "[$symbol$context ]($style)"

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "yellow"
